# Generated by Django 5.0.7 on 2024-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_gfg_options_remove_gfg_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gfg',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gfg',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
